### ISSUE TITLE
How I can create a new hypothesis?

### ISSUE THREAD

**Issue by mosoriob** [KnowledgeCaptureAndDiscovery/DISK-WEB#10]
I have started a new instance of DISK and I would like to create a hypothesis related to the bicycle rent example.

However, I cannot add a new hypothesis question.

Is the selector using a hardcoded list or fetch from the MediaWiki?

![image](https://user-images.githubusercontent.com/2365990/156764314-0b730bd5-945e-46b4-ae79-ef737089a838.png)

**Comment by mosoriob** [comment]
@hvarg https://media3.giphy.com/media/phJ6eMRFYI6CQ/giphy.gif?cid=36b14fac9f55k0td3lw1hk0229td6qh4lukgc4qtc0dv0zni&rid=giphy.gif&ct=g

**Comment by hvarg** [comment]
Questions are read directly from the ontology. You are still able to create an hypothesis, just ignore the question form and write down the triples directly.
If you want to create a question, you must follow the [scientific question ontology](https://knowledgecaptureanddiscovery.github.io/QuestionOntology/release/v1.0.0/index-en.html) and upload the `owl` file to some public place.
I'll work on adding the question source to the configuration file.

**Comment by hvarg** [comment]
You can add your own questions on the configuration file now:
https://github.com/KnowledgeCaptureAndDiscovery/DISK-WEB/commit/ace562846f2ce6fd732107081ffd25db2f721292
