### ISSUE TITLE
Use JSON (not ontology) to communicate with Wings

### ISSUE THREAD

**Issue by mosoriob** [KnowledgeCaptureAndDiscovery/DISK-WEB#23]

**Comment by mosoriob** [comment]
When the wings instance doesn't contain workflows, it sends an empty response. This is breaking the disk code

```
			KBAPI kb = fac.getKB(liburi, OntSpec.PLAIN);
```

**Comment by mosoriob** [comment]
➜  ~ curl  https://wings.dev.disk.isi.edu/wings-portal/export/users/admin/bikes_rent/workflows/library.owl 
# create a workflow
➜  ~ curl  https://wings.dev.disk.isi.edu/wings-portal/export/users/admin/bikes_rent/workflows/library.owl
<?xml version="1.0"?>
<rdf:RDF
    xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
    xmlns:j.0="http://www.wings-workflows.org/ontology/workflow.owl#"
      xml:base="http://localhost:8080/wings-portal/export/users/admin/bikes_rent/workflows/library.owl">
      <j.0:WorkflowTemplate rdf:about="bikes-rent.owl#bikes-rent"/>
</rdf:RDF>

**Comment by varunratnakar** [comment]
I would recommend you use the getTemplatesJSON api function:
Example: https://wings.dev.disk.isi.edu/wings-portal/users/admin/bikes_rent/workflows/getTemplatesListJSON

Note: you need to be logged in to Wings

**Comment by mosoriob** [comment]
Is it possible Hernan? Is it worth it?

**Comment by mosoriob** [comment]
@hvarg
