### ISSUE TITLE
Documenation - Check and implement Yolanda's comments.

### ISSUE THREAD

**Issue by mosoriob** [KnowledgeCaptureAndDiscovery/DISK-WEB#67]
- [x] Changes in the diagram in this page: https://disk.readthedocs.io/en/latest/concepts/ are in the attached slide.
- [x] In the documentation to create a LOI, I added a section "Specifying Workflows and Meta-Workflows” which is empty because I don’t know how that is done.
- [x] I cannot follow how to create a new question type, I sent a separate email about that.
- [ ] #76
- [x] In the installation instructions I think it is missing a command:
`   Sometimes the server is not responding. You can check the state of the server by running the following command: Open http://localhost:8080/disk-server/vocabulary to check that the local repository server is working fine. It might take a little while to open it for the first time as it downloads vocabularies from the internet.`
  
  
- [x] #68
- [x] I think the section “Adoptions” needs to be removed.
- [x] You should be mindful of the plurals when you write, for example this sentence: "This guide is for researchers who wants to create, manage and test hypothesis.” has 2 wrong plurals.

**Comment by mosoriob** [comment]
[DISK-Documentation-Changes-16July2022.pdf](https://github.com/KnowledgeCaptureAndDiscovery/DISK-WEB/files/9201092/DISK-Documentation-Changes-16July2022.pdf)

**Comment by mosoriob** [comment]
@hvarg do you editable draw of this image? 
![image](https://user-images.githubusercontent.com/2365990/181515523-18d51930-6933-4272-a943-a204b4c1cbf0.png)

**Comment by hvarg** [comment]
https://app.diagrams.net/#G1tyxfobXvFMVu6-cR-ivxUW2khm89Cr8y
